name: Pull Request automation
on:
  pull_request_target:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        if: ${{ github.event.action == 'opened' }}
        uses: kentaro-m/auto-assign-action@v1.1.2